const api = async (path, options = {}) => { const res = await fetch('/api/v1' + path, {headers:{'Content-Type':'application/json','X-User-ID':'web-editor','X-Role':'editor', ...(options.headers||{})}, ...options}); const body=await res.json(); if(!res.ok) throw new Error(body.message); return body.data };
const state={document:null,versions:[]};const workspace=document.querySelector('#workspace'),dialog=document.querySelector('#editor');
function escape(text=''){const el=document.createElement('span');el.textContent=text;return el.innerHTML}
async function loadDocuments(){const docs=await api('/documents');document.querySelector('#documents').innerHTML=docs.map(d=>`<button class="document ${state.document?.id===d.id?'active':''}" data-id="${d.id}"><strong>${escape(d.title)}</strong><br><small>版本更新于 ${new Date(d.updated_at).toLocaleString()}</small></button>`).join('')||'<p class="meta">暂无文档</p>';document.querySelectorAll('.document').forEach(b=>b.onclick=()=>openDocument(b.dataset.id))}
async function openDocument(id){state.document=await api('/documents/'+id);state.versions=await api('/documents/'+id+'/versions');const current=state.versions.at(-1);workspace.innerHTML=`<h2>${escape(state.document.title)}</h2><p class="meta">${escape(state.document.summary||'没有摘要')}</p><div class="toolbar"><button id="edit">提交新版本</button><button id="compare">比对最新两版</button></div><article class="content">${escape(current.content)}</article><div class="versions"><h2>版本时间线</h2>${state.versions.slice().reverse().map(v=>`<div class="version"><span>版本 ${v.number}${v.rollback_from_id?'（回滚）':''}<br><small>${escape(v.message||'未填写说明')}</small></span><small>${new Date(v.created_at).toLocaleString()}</small></div>`).join('')}</div>`;document.querySelector('#edit').onclick=()=>showEditor(current);document.querySelector('#compare').onclick=compare;loadDocuments()}
function showEditor(version){dialog.querySelector('#dialogTitle').textContent=version?'提交新版本':'新建文档';title.value=state.document?.title||'';summary.value=state.document?.summary||'';content.value=version?.content||'';messageWrap.style.display=version?'grid':'none';dialog.dataset.version=version?.number||'';dialog.showModal()}
async function save(){const version=Number(dialog.dataset.version);const payload={title:title.value,summary:summary.value,content:content.value,message:message.value,expected_version:version};try{if(version){await api('/documents/'+state.document.id+'/versions',{method:'POST',body:JSON.stringify(payload)});await openDocument(state.document.id)}else{const data=await api('/documents',{method:'POST',body:JSON.stringify(payload)});await openDocument(data.document.id)}dialog.close()}catch(error){alert(error.message)}}
async function compare(){if(state.versions.length<2){alert('至少需要两个版本');return}const [target,base]=state.versions.slice(-2);try{const job=await api('/comparisons',{method:'POST',body:JSON.stringify({base_version_id:base.id,target_version_id:target.id})});await new Promise(r=>setTimeout(r,150));const result=await api('/comparisons/'+job.id);alert('比对完成：'+Object.entries(result.result.summary).map(([k,v])=>k+' '+v).join('，'))}catch(error){alert(error.message)}}
newDocument.onclick=()=>showEditor(null);refresh.onclick=loadDocuments;save.onclick=e=>{e.preventDefault();save()};loadDocuments();
